export const applyJob = async (req,res) => {
    try {
         
    } catch (error) {
        console.log("Error in Applying",error.message);
        
    }
    
}